config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  post 'profiles/:id/edit', to: 'profiles#update', as: 'update'

  post 'galaxies/find_friends', to: 'galaxies#find_friends', as: 'find_friends'
  post 'galaxies/add_friend', to: 'galaxies#add_friend', as: 'add_friend'
  post 'galaxies/get_friends', to: 'galaxies#get_friends', as: 'get_friends'

  get 'user/{:id}', to: 'galaxies#get_user', as: 'get_user'
  resources :galaxies do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
    collection do
    end
  end

  get 'universe', to: 'galaxies#universe', as: 'universe' do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'home#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

app/models/galaxy.rb
class Galaxy < ActiveRecord::Base
  belongs_to :user
  has_one :privacy_level
  has_attached_file :photo, styles: { large: "600x600>", medium: "300x300", thumb: "150x150#"}
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def get_user(user_id)
    User.find(user_id)
  end

  def self.find_friends(search_for, current_user_id)
    user = User.arel_table
    query_string = "%#{search_for}%"
    return User.select(user[:id], user[:email])
               .where(user[:email].matches(query_string))
               .where(user[:id].not_eq(current_user_id))
               .where("id NOT IN (SELECT user_id AS friendID FROM #{:friends} WHERE #{:friend_id} = #{current_user_id} UNION SELECT #{:friend_id} AS friendID FROM #{:friends} WHERE user_id = #{current_user_id})")
               .order(user[:email])
  end

  def self.add_friend(sender_id, receiver_id)
    ActiveRecord::Base.transaction do
      Friend.find_or_create_by(user_id: sender_id, friend_id: receiver_id)
      add_notification(sender_id, receiver_id, 1)
    end
  end

  def self.get_friends(current_user_id)
    User.where("id IN (SELECT #{:user_id} AS friendID FROM #{:friends} WHERE #{:friend_id} = #{current_user_id} UNION SELECT #{:friend_id} AS friendID FROM #{:friends} WHERE #{:user_id} = #{current_user_id})").order(:fName)
  end

  def self.add_notification(sender_id, receiver_id, notification_id)
    Notification.find_or_create_by(sender_id: sender_id, receiver_id: receiver_id, notification_type_id: notification_id)
  end

  def self.get_notification_count(receiver_id)
    Notification.where(receiver_id: receiver_id).where(viewed: nil).count
  end

  def self.get_notifications(receiver_id)
    @notifications = NotificationType.select('*').joins(:users).where('notifications.receiver_id = ?', receiver_id).where('notifications.viewed IS NULL')#notification_types.short, notifications.sender_id, notifications.created_at, notifications.viewed
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user, foreign_key: :sender_id
  belongs_to :notification_type, foreign_key: :notification_type_id
end

app/models/notification_type.rb
class NotificationType < ActiveRecord::Base
  has_many :notifications, foreign_key: :notification_type_id
  has_many :users, :through => :notifications
end

app/models/privacy_level.rb
class PrivacyLevel < ActiveRecord::Base
  belongs_to :galaxy

  def display_privacy_levels
    "#{display} - #{description}"
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Added confirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_one :galaxy
  has_many :friends
  has_many :notifications, foreign_key: :receiver_id
  has_many :notification_types, :through => :notifications#, source: :receiver_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :foo

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || galaxies_path
  end

  def execute_statement(sql)
    results = ActiveRecord::Base.connection.execute(sql)
    if results.present?
      return results
    else
      return nil
    end
  end

  def foo
    @notification_count = Galaxy.get_notification_count(current_user)
    @notifications = Galaxy.get_notifications(current_user)
  end
end

app/controllers/galaxies_controller.rb
class GalaxiesController < ApplicationController
  before_action :set_galaxy, only: [:show, :edit, :update, :destroy], except: :universe
  before_action :get_friends, only: [:index, :universe]
  before_action :authenticate_user!

  respond_to :html

  def index
    if params[:user_id] && User.find(params[:user_id])
      @user = User.find(params[:user_id])
    else
      @user = current_user
    end
    page = params[:page].to_i
    @galaxies = Galaxy.where(author: [@user.id]).order("created_at desc").page(page).per(5)
    respond_with(@galaxies)
  end

  def universe
    page = params[:page].to_i
    @universe_ids = [current_user.id]
    @friends.each do |friend|
      @universe_ids << friend.id
    end
    @galaxies = Galaxy.where(author: [@universe_ids]).order("created_at desc").page(page).per(5)
    respond_with(@galaxies)
  end

  def show
    respond_with(@galaxy)
  end

  def new
    @galaxy = Galaxy.new
    respond_with(@galaxy)
  end

  def edit
  end

  def create
    @galaxy = Galaxy.new(galaxy_params)
    @galaxy.save
    redirect_to(galaxies_path)
  end

  def update
    @galaxy.update(galaxy_params)
    redirect_to(galaxies_path)
  end

  def destroy
    @galaxy.destroy
    respond_with(@galaxy)
  end

  def find_friends
    if params.has_key?(:find_friends) && params[:find_friends] != ''
      find_friends = Galaxy.find_friends(params[:find_friends], current_user.id)
      @found_friends = Array.new
      find_friends.find_each do |friend|
        @found_friends << friend
      end
      # respond_to :js
    else
      respond_to do |format|
        format.js { render file: 'galaxies/find_friends_empty' }
      end
      # render :nothing => true, :status => :ok
    end
  end

  def add_friend
    if params.has_key?(:friend_id) && params.has_key?(:friend_email)
      @add_friend = params
      Galaxy.add_friend(current_user.id, params[:friend_id])
    else
      render :nothing => true, :status => :ok
    end
  end

  def get_friends
    friends = Galaxy.get_friends(current_user.id)
    @friends = Array.new
    friends.find_each do |friend|
      @friends << friend
    end

    if params[:user_id] && params[:user_id] != current_user.id && User.find(params[:user_id])
      friends_of_other = Galaxy.get_friends(params[:user_id])
      @friends_of_other = Array.new
      friends_of_other.find_each do |friend_of_other|
        @friends_of_other << friend_of_other
      end
    end
  end

  private

  def set_galaxy
    @galaxy = Galaxy.find(params[:id])
  end

  def galaxy_params
    params.require(:galaxy).permit(:author, :content, :image, :tag, :privacy_id, :photo)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    redirect_to profile_path(current_user.id)
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    redirect_to profile_path(current_user.id)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:fName, :lName, :age, :dob, :avatar, :comments)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:fName, :lName, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:fName, :lName, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galaxies_helper.rb
module GalaxiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/galaxies/_add_friends.html.erb
<div class="red">Added Friend <%= @add_friend[:friend_email] %></div>

app/views/galaxies/_find_friends.html.erb
<%= content_tag( 'div','<i class="fa fa-times-circle-o"></i>'.html_safe, id: 'findFriendsResultsClose') %>
<h3>Find Friends</h3>
<% if friends.count > 0 %>
    <% friends.each do |friend| %>
        <%= form_tag(add_friend_path, method: 'post', id: "add_friend_#{friend.id}", :remote => true) do %>
            <%= friend.email %> <%= hidden_field_tag 'friend_email', friend.email %><%= hidden_field_tag 'friend_id', friend.id %><%= submit_tag 'Add Friend', class: 'makeButton' %>
        <% end %>
    <% end %>
<% else %>
    Sorry, but we didn't find anyone.
<% end %>

app/views/galaxies/_form.html.erb
<%= form_for @galaxy, :html => {:multipart => true} do |f| %>
    <% if @galaxy.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@galaxy.errors.count, "error") %> prohibited this galaxy from being saved:</h2>

          <ul>
            <% @galaxy.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div id="galaxy_form">
      <div class="field">
        <%= f.hidden_field :author, value: current_user.id %><br>
      </div>
      <div class="field">
        <%= f.label :content %><br>
        <%= f.text_area :content %>
      </div>
      <div class="field">
        <%= f.label :privacy_level %><br>
        <%= f.collection_select :privacy_id, PrivacyLevel.all, :id, :display_privacy_levels, {:selected => "3"} %>
      </div>
      <div>
        <%= f.file_field :photo %>
      </div>
      <div class="field">
        <%= f.label :tag %><br>
        <%= f.text_field :tag %>
      </div>
    </div>

    <div class="actions">
      <% if action_name == 'edit' %>
          <%= submit_tag 'Update Post' %>
      <% else %>
          <%= submit_tag 'Save Post' %>
      <% end %>
    </div>
<% end %>

app/views/galaxies/add_friend.js.erb
/**
 * Created by markproaudio on 2/14/16.
 */
$("form#add_friend_<%= @add_friend[:friend_id] %>").before("<%= j render partial: 'add_friends' %>").remove();
$("#myFriends ul").prepend("<%= @add_friend[:friend_email] %>")

app/views/galaxies/edit.html.erb
<h1>Editing galaxy</h1>

<%= render 'form' %>

<%= link_to 'Show', @galaxy %> |
<%= link_to 'Back', galaxies_path %>

app/views/galaxies/find_friends.js.erb
/**
 * Created by markproaudio on 2/11/16.
 */
$("#findFriendsResults").show().html("<%= j render partial: 'find_friends', :locals => { friends: @found_friends} %>");

app/views/galaxies/find_friends_empty.js.erb
/**
 * Created by markproaudio on 2/11/16.
 */
$("#findFriendsResults").html("").hide();

app/views/galaxies/index.html.erb
<div id="galaxyStyle">
<div id="galaxyTopContainer">
  <% if @user && @user.id == current_user.id %>
      <h1>My Galaxy</h1>
  <% end %>
  <%= form_tag(find_friends_path, method: 'post', id: 'findFriendsForm', :remote => true) do %>
      <%= text_field_tag(:find_friends) %>
      <%= submit_tag 'Find Friends' %>
  <% end %>
  <%= content_tag 'div', '', id: 'findFriendsResults' %>
  <% if @user && @user.email %>
      <h2><%= @user.fName %>'s Galaxy</h2>
  <% end %>
  <%= link_to 'New Post', new_galaxy_path, class: 'makeButton' %>
</div>
<div id="galaxies" class="border"><span><%= paginate @galaxies %></span>
<% @galaxies.each do |galaxy| %>
    <div class='galaxy'>
      <% if galaxy.photo_file_name != nil %>
          <%= image_tag galaxy.photo.url(:medium) %>
      <% end %>
      <p>
        <span><%= galaxy.get_user(galaxy.author).fName %>:&nbsp;<%= time_ago_in_words(galaxy.created_at) %> ago &nbsp;</span><br>
        <%= galaxy.content %></p>
      <% if galaxy.author == current_user.id %>
          <%= link_to 'Edit', edit_galaxy_path(galaxy) %>
          <%= link_to 'Delete', galaxy, method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </div>
<% end %>
</div>
<div id="myFriends">
  <% if @user && @user.id != current_user.id %>
      <h3><%= @user.email %>'s Friends</h3>
      <ul>
        <% @friends_of_other.each do |friend_of_other| %>
            <li>
              <%= link_to friend_of_other.email, :action => 'index', :user_id => friend_of_other.id %>
            </li>
        <% end %>
      </ul>
  <% else %>
      <h3>My Friends</h3>
      <ul>
        <% @friends.each do |friend| %>
            <li>
              <%= link_to friend.email, :action => 'index', :user_id => friend.id %>
            </li>
        <% end %>
      </ul>
  <% end %>
</div>
</div>

app/views/galaxies/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', galaxies_path %>

app/views/galaxies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @galaxy.author %>
</p>
<br/>

<p>
  <strong>Image:</strong><br/>
  <%= image_tag @galaxies.image_url(:thumb).to_s %><br/>
  <%= @galaxy.image %>
</p>
<br/>
<p>
  <strong>Content:</strong>
  <%= @galaxy.content %>
</p>
<br/>
<p>
  <strong>Tag:</strong>
  <%= @galaxy.tag %>
</p>
<br/>
<%= link_to 'Edit', edit_galaxy_path(@galaxy) %> |
<%= link_to 'Back', galaxies_path %>

app/views/galaxies/universe.html.erb
<div id="galaxyTopContainer">
  <h1>My Universe</h1>
  <%= form_tag(find_friends_path, method: 'post', id: 'findFriendsForm', :remote => true) do %>
      <%= text_field_tag(:find_friends) %>
      <%= submit_tag 'Find Friends' %>
  <% end %>
  <%= content_tag 'div', '', id: 'findFriendsResults' %>
  <% if (current_user && current_user.email) %>
      <h2><%= current_user.fName %>'s Universe</h2>
  <% end %>
  <%= link_to 'New Post', new_galaxy_path, class: 'makeButton' %>
</div>
<div id="galaxies"><span><%= paginate @galaxies %></span>
  <% @galaxies.each do |galaxy| %>
      <div class='galaxy'>
        <% if galaxy.photo_file_name != nil %>
            <%= image_tag galaxy.photo.url(:medium) %>
        <% end %>
        <p>
          <span><%= galaxy.get_user(galaxy.author).fName %>:&nbsp;<%= time_ago_in_words(galaxy.created_at) %> ago &nbsp;</span>
          <% # This get_user() method is kind of lame, but galaxy.user returns nil  %>
          <%= galaxy.content %></p>
        <% if galaxy.author == current_user.id %>
            <%= link_to 'Edit', edit_galaxy_path(galaxy) %>
            <%= link_to 'Delete', galaxy, method: :delete, data: {confirm: 'Are you sure?'} %>
        <% end %>
      </div>
  <% end %>
</div>
<div id="myFriends">
  <h3>My Friends</h3>
  <ul>
    <% @friends.each do |friend| %>
        <li>
          <%= link_to friend.fName + " " + friend.lName , :action => 'index', :user_id => friend.id %>
        </li>
    <% end %>
  </ul>
</div>

app/views/home/index.html.erb
<div id="homeWrapper">
  <div id="contentsHome">
    <div id="adbox">
      <div class="wrapper clearfix1">
        <div class="info">
          <h1>Spacebook</h1>
        </div>
      </div>
      <%= image_tag 'bg-adbox.jpg' %>
      <div class="highlight">
        <h2>Keep in Contact with the World - <i>Privacy is our #1 goal!</i></h2>
      </div>
    </div>
    <div id="infoP">
      <div class="click-here">
        <h1>Get Your Own Account Now!</h1>
        <%= link_to 'Click Here!', new_user_registration_path, class: 'btn2' %>
      </div>
      <h1 id="welcome">
        Welcome to SpaceBook
      </h1>
      <p id="last">
        SpaceBook is a new social media platform designed to not irritate you. Do you like sand? How about a nagging
        mother-in-law? We don't , and we think that social media platforms shouldn't be either. Instead of tracking your
        movements across the internet and scaring you with ads for that lingerie you just looked at, we respect your
        privacy by not sharing your activities with third parties. You get to decide what is shared once and for all.
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>Spacebook</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/header' %>
<div id="content">
  <% if notice.blank? %>
      <% notice_class = ' hide' %>
  <% end %>
  <% if alert.blank? %>
      <% alert_class = ' hide' %>
  <% end %>
  <p class="notice<%= notice_class %>"><%= notice %></p>
  <p class="alert<%= alert_class %>"><%= alert %></p>
  <%= yield %>
</div>
<%= render 'shared/footer' %>
</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@user, :url => edit_profile_path, :html => {:method => :post}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fName %><br>
    <%= f.text_field :fName %>
  </div>
    <div class="field">
      <%= f.label :lName %><br>
      <%= f.text_field :lName %>
    </div>
    <div class="field">
      <%= f.label :avatar %><br>
      <%= f.text_field :avatar %>
    </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.text_field :dob %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', profiles_path(@user) %>

app/views/profiles/index.html.erb
<h1>New Profile</h1>

<p>Create New profile</p>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div id="showPage">

  <div id="wrapper">
    <div id="avatar">
      <% if @user.avatar != nil %>
          <%= image_tag @user.avatar %>

      <% else%>
          <%= image_tag 'missing.jpg' %>

      <% end %>

    </div>

    <div id="fname">
      <strong>First Name:</strong><%= @user.fName %>
    </div>

    <div id="fname">
      <strong>Last Name:</strong>
      <%= @user.lName %>
    </div>

    <div>
      <strong>Email:</strong>
      <%= @user.email %>
    </div>

    <div>
      <strong>Age:</strong>
      <%= @user.age %>
    </div>

    <div>
      <strong>Dob:</strong>
      <%= @user.dob %>
    </div>

  </div>

  <div id="comment">
    <strong>Comment</strong></br>
    <%= @user.comments %>
  </div>

    <%= link_to 'Edit', edit_profile_path(@user) %>





</div>

app/views/shared/_footer.html.erb
<footer>
      <p id="copy">
        © Copyright SpaceRangers 2016<br>
        All Rights Reserved
      </p>
</footer>

app/views/shared/_header.html.erb
<header>
  <%= image_tag 'logo.png', id: 'logo' %>
  <%= render 'shared/notifications' %>
  <%= render 'shared/nav' %>
</header>

app/views/shared/_nav.html.erb
<nav>
  <nav>
    <ul id="menu">
      <li>
        <%= link_to('Home', root_path) %>
      </li>
      <% if user_signed_in? %>
          <li><%= link_to("Logout", destroy_user_session_path, method: "delete") %></li>
          <li>
            <%= link_to "My Profile", profiles_path %>
          </li>
          <li>
            <%= link_to "My Galaxy", galaxies_path %>
          </li>
          <li>
            <%= link_to "My Universe", universe_path %>
          </li>
      <% else %>
          <li><%= link_to("Login", new_user_session_path) %></li>
          <li>
            <%= link_to 'Register', new_user_registration_path %>
          </li>
    <% end %>
    </ul>
  </nav>
</nav>

app/views/shared/_notifications.html.erb
<%= content_tag :div, id: 'notificationsContainer' do %>
    <% if @notification_count > 0 %>
        <div class="toggleButton">Notifications
          <div id="notificationsCount"><%= @notification_count %></div>
        </div>
        <div class="toggleMe" id="notifications">
          <% @notifications.each do |notification| %>
              <% notificationMessage = link_to notification.fName + ' ' + notification.lName, :action => 'index', :user_id => notification.sender_id %>
              <% if notification.short == 'friend request' %>
                  <% notificationMessage += ' sent you a friend request.' %>
              <% end %>
              <%= content_tag :div, notificationMessage, class: 'notificationMessage' %>
          <% end %>
        </div>
    <% end %>
<% end %>